"""Trade signal SSE route handlers."""

from __future__ import annotations

import asyncio
import json
from datetime import datetime, timedelta, timezone
from typing import AsyncGenerator, List

from fastapi import APIRouter
from fastapi.responses import StreamingResponse

from api.models import TradeSetup
from api.store import redis_store
from src.config import MongoConfig, SETUPS_MONGO_DB
from src.storage import MongoStore

router = APIRouter(tags=["Setups"])

_SIGNALS_KEY = "coinr:trade_signals:recent"
_EVENTS_CHANNEL = "coinr:trade_signals:events"
_SIGNAL_TTL_SECONDS = 7200  # 120 minutes
_HISTORY_WINDOW_HOURS = 48
_HISTORY_CACHE_KEY = "history:setups:48h:v1"
_HISTORY_CACHE_TTL_SECONDS = 300


def _serialize_position(position: dict) -> dict:
    payload = dict(position)
    timestamp = payload.get("timestamp")
    if isinstance(timestamp, datetime):
        if timestamp.tzinfo is None:
            timestamp = timestamp.replace(tzinfo=timezone.utc)
        payload["timestamp"] = timestamp.isoformat()
    return payload


def _parse_timestamp(value: str) -> datetime | None:
    try:
        timestamp = datetime.fromisoformat(value.replace("Z", "+00:00"))
    except (TypeError, ValueError, AttributeError):
        return None
    if timestamp.tzinfo is None:
        timestamp = timestamp.replace(tzinfo=timezone.utc)
    return timestamp


def _is_expired_setup(setup: TradeSetup, now: datetime) -> bool:
    timestamp = _parse_timestamp(setup.timestamp)
    if timestamp is None:
        return True
    return timestamp + timedelta(minutes=max(setup.valid_for_minutes, 0)) <= now


def _load_setup_history() -> list[dict]:
    base_mongo_cfg = MongoConfig()
    setups_mongo_cfg = MongoConfig(uri=base_mongo_cfg.uri, database=SETUPS_MONGO_DB)
    cutoff = datetime.now(timezone.utc) - timedelta(hours=_HISTORY_WINDOW_HOURS)
    store = MongoStore(setups_mongo_cfg)
    return store.find(
        "analyses",
        query={"timestamp": {"$gte": cutoff}, "position": {"$ne": None}},
        projection={"_id": 0, "position": 1},
        sort=[("timestamp", -1)],
    )


def _format_sse(payload: object) -> str:
    return f"data: {json.dumps(payload, separators=(',', ':'))}\n\n"


async def _stream_signals() -> AsyncGenerator[str, None]:
    q = await redis_store.subscribe(_EVENTS_CHANNEL)
    try:
        # Emit currently active signals immediately on connect
        active = await redis_store.get_recent_signals(_SIGNALS_KEY, _SIGNAL_TTL_SECONDS)
        for signal in active:
            yield _format_sse(signal)

        # Stream new signals in real-time — the hub delivers raw JSON data
        while True:
            try:
                data = await asyncio.wait_for(q.get(), timeout=30)
            except asyncio.TimeoutError:
                yield 'data: {"type":"keepalive"}\n\n'  # refreshes client stale clock
                continue
            try:
                payload = json.loads(data)
                yield _format_sse(payload)
            except (json.JSONDecodeError, TypeError):
                pass
            await asyncio.sleep(0)
    except asyncio.CancelledError:
        raise
    finally:
        await redis_store.unsubscribe(_EVENTS_CHANNEL, q)


@router.get(
    "/setups/stream",
    summary="Stream trade setups",
    description="""
Server-Sent Events stream. On connect, emits all active setups from the last
120 minutes, then streams new setups in real-time as they are generated by
the analysis agent.

Each SSE frame: `data: <TradeSetup JSON>\\n\\n`
""",
    response_class=StreamingResponse,
    responses={
        200: {
            "description": "Continuous SSE stream. Each frame: `data: <TradeSetup JSON>\\n\\n`.",
            "content": {
                "text/event-stream": {
                    "schema": TradeSetup.model_json_schema(),
                }
            },
        }
    },
)
async def sse_setups() -> StreamingResponse:
    return StreamingResponse(
        _stream_signals(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "Connection": "keep-alive"},
    )


@router.get(
    "/setups",
    summary="Get active trade setups",
    description="Returns all trade setups from the last 120 minutes, oldest first.",
    response_model=List[TradeSetup],
)
async def setups_active() -> list:
    return await redis_store.get_recent_signals(_SIGNALS_KEY, _SIGNAL_TTL_SECONDS)


@router.get(
    "/setups/history",
    summary="Get setup history for the last 48 hours",
    description="""
Returns expired trade setups from the last 48 hours, newest first.

Only analysis records with a non-null `position` are included, and setups that
are still within their `valid_for_minutes` window are excluded. Each item is
returned as a `TradeSetup` payload without the outer analysis envelope.
""",
    response_model=List[TradeSetup],
)
async def setups_history() -> list[TradeSetup]:
    cached = await redis_store.get_json(_HISTORY_CACHE_KEY)
    if cached is not None:
        return [TradeSetup.model_validate(item) for item in cached]

    history = await asyncio.to_thread(_load_setup_history)
    now = datetime.now(timezone.utc)
    payload = [
        setup
        for item in history
        if item.get("position") is not None
        for setup in [TradeSetup.model_validate(_serialize_position(item["position"]))]
        if _is_expired_setup(setup, now)
    ]
    await redis_store.set_json(
        _HISTORY_CACHE_KEY,
        [item.model_dump(mode="json") for item in payload],
        ex=_HISTORY_CACHE_TTL_SECONDS,
    )
    return payload
