"""Trade signal SSE route handlers."""

from __future__ import annotations

import asyncio
import json
from typing import AsyncGenerator, List

from fastapi import APIRouter
from fastapi.responses import StreamingResponse

from api.models import TradeSetup
from api.store import redis_store

router = APIRouter(tags=["Setups"])

_SIGNALS_KEY = "coinr:trade_signals:recent"
_EVENTS_CHANNEL = "coinr:trade_signals:events"
_SIGNAL_TTL_SECONDS = 7200  # 120 minutes


def _format_sse(payload: object) -> str:
    return f"data: {json.dumps(payload, separators=(',', ':'))}\n\n"


async def _stream_signals() -> AsyncGenerator[str, None]:
    q = await redis_store.subscribe(_EVENTS_CHANNEL)
    try:
        # Emit currently active signals immediately on connect
        active = await redis_store.get_recent_signals(_SIGNALS_KEY, _SIGNAL_TTL_SECONDS)
        for signal in active:
            yield _format_sse(signal)

        # Stream new signals in real-time — the hub delivers raw JSON data
        while True:
            try:
                data = await asyncio.wait_for(q.get(), timeout=30)
            except asyncio.TimeoutError:
                yield 'data: {"type":"keepalive"}\n\n'  # refreshes client stale clock
                continue
            try:
                payload = json.loads(data)
                yield _format_sse(payload)
            except (json.JSONDecodeError, TypeError):
                pass
            await asyncio.sleep(0)
    except asyncio.CancelledError:
        raise
    finally:
        await redis_store.unsubscribe(_EVENTS_CHANNEL, q)


@router.get(
    "/setups/stream",
    summary="Stream trade setups",
    description="""
Server-Sent Events stream. On connect, emits all active setups from the last
120 minutes, then streams new setups in real-time as they are generated by
the analysis agent.

Each SSE frame: `data: <TradeSetup JSON>\\n\\n`
""",
    response_class=StreamingResponse,
    responses={
        200: {
            "description": "Continuous SSE stream. Each frame: `data: <TradeSetup JSON>\\n\\n`.",
            "content": {
                "text/event-stream": {
                    "schema": TradeSetup.model_json_schema(),
                }
            },
        }
    },
)
async def sse_setups() -> StreamingResponse:
    return StreamingResponse(
        _stream_signals(),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "Connection": "keep-alive"},
    )


@router.get(
    "/setups",
    summary="Get active trade setups",
    description="Returns all trade setups from the last 120 minutes, oldest first.",
    response_model=List[TradeSetup],
)
async def setups_active() -> list:
    return await redis_store.get_recent_signals(_SIGNALS_KEY, _SIGNAL_TTL_SECONDS)
